pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
	# Home page
	path('', views.index, name='index'),
]

todos/urls.py
from django.urls import path

from . import views


urlpatterns = [
	path('', views.TodosView.as_view(), name='todos'),
]

unitodos/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import (
    bad_request_view, permission_denied_view
    )


urlpatterns = [
    path('admin/', admin.site.urls),

    # users app
    path('account/', include(('users.urls', 'users'), namespace='users')),

    # pages app
    path('', include(('pages.urls', 'pages'), namespace='pages')),

    # todos app
    path('todos/', include(('todos.urls', 'todos'), namespace='todos')),
]

# Error views
handler404 = bad_request_view
handler403 = permission_denied_view

users/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # Log in page
    path('login/', views.LoginView.as_view(), name='login'),
    # Log out page
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # Sign up page
    path('signup/', views.SignupFormView.as_view(), name='signup'),
    # Sign up success page
    path('signup-success/', views.SignupSuccessView.as_view(), name='signup-success')
]

pages/models.py
from django.db import models

# Create your models here.

todos/models.py
from django.conf import settings
from django.db import models


class Module(models.Model):
    name = models.CharField(max_length=120)
    code = models.CharField(max_length=40, blank=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        if self.code == '':
            return self.name
        return f'{self.code}: {self.name}'

    class Meta:
        unique_together = ['id', 'owner']


class BaseTodo(models.Model):
    is_done = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE
    )

    class Meta:
        abstract = True


class LectureTodo(BaseTodo):
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    topic = models.CharField(max_length=120, blank=True)
    lecture_date = models.DateField(blank=True, null=True)
    duration = models.PositiveSmallIntegerField(blank=True, null=True)

    def __str__(self):
        if self.topic == '' and self.lecture_date is None:
            return f'{self.module.name} | Lecture {self.id}'
        elif self.topic == '' and self.lecture_date is not None:
            return f'Lecture from {self.lecture_date}'
        elif self.topic != '' and self.lecture_date is None:
            return f'Lecture on {self.topic}'
        else:
            return f'{self.topic}: {self.lecture_date}'

    @property
    def as_module_and_id(self):
        if self.module.code != '':
            return f'{self.module.code} | Lecture {self.id}'
        else:
            return f'{self.module.name} | Lecture {self.id}'

users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class UserProfile(models.Model):
    owner = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True
    )
    university = models.CharField(
        max_length=80,
        choices=settings.UNIVERSITIES,
        blank=True,
        null=True
    )

    def __str__(self):
        return f'Profile of {self.owner}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm as DjUserCreationForm
from .models import User, UserProfile


class UserCreationForm(DjUserCreationForm):
    class Meta(DjUserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        # Save user and store it to return later
        new_user = super().save(commit=commit)
        # Create user profile
        UserProfile.objects.create(owner=new_user)
        # Return saved user
        return new_user

pages/views.py
from django.shortcuts import render


def index(request):
	return render(request, 'pages/index.html')

def bad_request_view(request, exception):
	return render(request, 'pages/404.html', status=404)

def permission_denied_view(request, exception):
	return render(request, 'pages/403.html', status=403)

todos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView

from .models import LectureTodo


class TodosView(LoginRequiredMixin, TemplateView):
	template_name = "todos/todos.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['lecture_todos'] = LectureTodo.objects.all()
		return context

users/views.py
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth import authenticate, login
from django.http import HttpResponseNotAllowed
from django.shortcuts import redirect
from django.urls import reverse_lazy

from .forms import UserCreationForm


class LoginView(auth_views.LoginView):
	template_name = 'userauth/login.html'
	redirect_authenticated_user = True

	def dispatch(self, request, *args, **kwargs):
		"""Don't let the user log in if already authenticated"""
		if request.user.is_authenticated:
			return redirect('pages:index')
		return super().dispatch(request, *args, **kwargs)


# TODO: Add 'successfully logged out view'
class LogoutView(auth_views.LogoutView):
	template_name = 'userauth/logout.html'

	def get(self, *args, **kwargs):
		"""
		A GET request to logout view should return a HTTP status code of
		405 Method Not Allowed, as we want logout to be only possible
		with a POST request, not GET.
		"""
		return HttpResponseNotAllowed(['POST'])


class SignupFormView(FormView):
	template_name = 'userauth/signup.html'
	form_class = UserCreationForm
	success_url = reverse_lazy('users:signup-success')

	def form_valid(self, form):
		"""
		Received a valid user creation form, authenticate and save the user, 
		log them in, keep track of their signup status through session info 
		and redirect them to the success page.
		"""
		# Save the user
		form.save()
		# Authenticate user
		username = self.request.POST['username']
		password = self.request.POST['password1']
		user = authenticate(username=username, password=password)
		# Log them in
		login(self.request, user)
		# Set signup tracking flag
		self.request.session['signup_complete'] = True
		return super().form_valid(form)

	def dispatch(self, request, *args, **kwargs):
		"""Don't let the user sign up if they are already logged in"""
		if request.user.is_authenticated:
			return redirect('pages:index')
		return super().dispatch(request, *args, **kwargs)


class SignupSuccessView(TemplateView):
	template_name = 'userauth/signup_success.html'

	def dispatch(self, request, *args, **kwargs):
		"""Check if the user came here after signing up"""
		if request.session.pop('signup_complete', False):  # signed up
			return super().dispatch(request, *args, **kwargs)
		return redirect('users:signup')

pages/templates/pages/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{% block title %}{% endblock title %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- TODO: favicon and project's own css files here -->

		{% bootstrap_css %}
    {% block head %}
    {% endblock head %}
	</head>
	<body>
    {% block navbar %}
    {% endblock navbar %}

		<div id="header-div">
			{% block header %}
			{% endblock header %}
		</div>
		<div id="content-div">
			{% block content %}
			{% endblock content %}
		</div>

    <!-- Scripts and JQuery (for Bootstrap) -->
		{% bootstrap_javascript jquery='full' %}
    {% block scripts %}
    {% endblock scripts %}
	</body>
</html>

pages/templates/pages/index.html
{% extends "pages/navbar.html" %}

{% block title %}Unitodos | Home Page{% endblock title %}

{% block header %}
<h1>Header Content</h1>
{% endblock header %}

{% block content %}

<p>Home Page</p>

{% endblock content %}

pages/templates/pages/navbar.html
{% extends "pages/base.html" %}
{% load bootstrap4 %}

{% block navbar %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Unitodos</a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'pages:index' %}">Home</a>
    </li>
    <!-- Authentication-related links -->
    {% if user.is_authenticated %}
    <li class="nav-item">
      <form name="logoutForm" class="form-inline" method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <a class="nav-link" href="javascript:submitLogoutForm()">Log out</a>
      </form>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'todos:todos' %}">Todos</a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'users:signup' %}">Sign up</a>
    </li>
    {% endif %}
  </div>
</nav>
{% endblock navbar %}

{% block scripts %}
<script type="text/javascript">
function submitLogoutForm() {
  document.logoutForm.submit();
}
</script>
{% endblock scripts %}

todos/templates/todos/todos.html
{% extends "pages/navbar.html" %}
{% load bootstrap4 %}


{% block head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style type="text/css">
.todo-text {
  font-size: 1.5em;
}
</style>
{% endblock head %}


{% block title %}All Todos{% endblock title %}


{% block header %}
<h1>All Todos</h1>
{% endblock header %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col">
      <div class="card">
        <div class="card-header">
          <span class="font-weight-bold">Lecture Todos</span>
        </div>

  			<ul class="list-group list-group-flush">
  				{% for todo in lecture_todos %}
            {% if forloop.counter0|divisibleby:2 %}
  					<li class="list-group-item list-group-item-light">
            {% else %}
            <li class="list-group-item list-group-item-dark">
            {% endif %}
              <i class="fa fa-2x fa-square-o p-1"></i>
              <span class="todo-text container-fluid d-inline ml-3">{{ todo }}</span>
            </li>
  				{% endfor %}
  			</ul>
      </div>
		</div>
		<div class="col">
			<!-- Empty for now, different todo list here -->
		</div>
	</div>
</div>
{% endblock content %}

users/templates/userauth/login.html
{% extends "pages/base.html" %}
{% load bootstrap4 %}

{% block title %}Log in{% endblock title %}

{% block header %}
  <h1>Log in</h1>
  {% bootstrap_messages %}
{% endblock header %}

{% block content %}

<form method="post" action="{% url 'users:login' %}">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button name="submit">Log in</button>
  {% endbuttons %}
  <input type="hidden" name="next" value="{{ next }}"/>
</form>

{% endblock content %}

users/templates/userauth/logout.html
{% extends "pages/base.html" %}
{% load bootstrap4 %}

{% block title %}Successfully logged out{% endblock title %}

{% block content %}
<p>Logged out</p>
<p>Click to go back to the <a href="{% url 'pages:index' %}">Home Page</a></p>

{% endblock content %}

users/templates/userauth/profile.html
{% extends "pages/base.html" %}

{% block header %}
<h1>Profile</h1>
{% endblock header %}

{% block content %}
<a>Change password</a><br/>
<a>Reset password</a><br/>
<a>Change password</a><br/>
<a>Change password</a><br/>
{% endblock content %}

users/templates/userauth/signup.html
{% extends "pages/base.html" %}
{% load bootstrap4 %}

{% block title %}Sign up{% endblock title %}

{% block header %}
  <h1>Sign up here</h1>
{% endblock header %}

{% block content %}

<form method="post" action="{% url 'users:signup' %}">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button name="submit">Sign up</button>
  {% endbuttons %}
</form>

{% endblock content %}

users/templates/userauth/signup_success.html
{% extends "pages/base.html" %}

{% block title %}Succesfully signed up{% endblock title %}

{% block content %}

<h3>You have succesfully logged in.</h3>
<p><a href="{% url 'pages:index' %}">Click here to go back to home page</a></p>

{% endblock content %}